export const dificulty = {
  intermedio: {
    color: 'bg-orange-400',
  },
  principiante: {
    color: 'bg-green-400',
  },
  avanzado: {
    color: 'bg-red-400',
  },
}

export interface Challenge {
  id: string
  dificulty: keyof typeof dificulty
  title: string
  description: string
  date: string // Podrías usar Date si parseás el string
  time: string
  participants: number
  maxParticipants: number
  stacks: string[]
  value: number
}

export const challenges: Challenge[] = [
  {
    id: '1',
    dificulty: 'principiante',
    title: 'Introducción a React',
    description:
      'Aprende los fundamentos de React creando tu primera aplicación.',
    date: '2024-07-01',
    time: '18:00',
    participants: 10,
    maxParticipants: 20,
    stacks: ['React', 'JavaScript', 'HTML', 'CSS'],
    value: 4.5,
  },
  {
    id: '2',
    dificulty: 'intermedio',
    title: 'API REST con Node.js',
    description: 'Construye una API RESTful utilizando Node.js y Express.',
    date: '2024-07-05',
    time: '17:00',
    participants: 8,
    maxParticipants: 15,
    stacks: ['Node.js', 'Express', 'MongoDB'],
    value: 4.0,
  },
  {
    id: '3',
    dificulty: 'avanzado',
    title: 'Despliegue en la nube',
    description:
      'Aprende a desplegar aplicaciones en AWS usando Docker y CI/CD.',
    date: '2024-07-10',
    time: '19:30',
    participants: 5,
    maxParticipants: 10,
    stacks: ['AWS', 'Docker', 'CI/CD', 'GitHub Actions', 'TypeScript'],
    value: 5.0,
  },
  {
    id: '4',
    dificulty: 'principiante',
    title: 'Fundamentos de HTML y CSS',
    description: 'Crea páginas web estáticas usando HTML5 y CSS3.',
    date: '2024-07-12',
    time: '16:00',
    participants: 12,
    maxParticipants: 25,
    stacks: ['HTML', 'CSS'],
    value: 4.2,
  },
  {
    id: '5',
    dificulty: 'intermedio',
    title: 'Gestión de estado en React',
    description: 'Aprende a manejar el estado global con Redux.',
    date: '2024-07-15',
    time: '18:30',
    participants: 9,
    maxParticipants: 18,
    stacks: ['React', 'Redux', 'JavaScript'],
    value: 4.3,
  },
  {
    id: '6',
    dificulty: 'avanzado',
    title: 'Microservicios con Node.js',
    description: 'Implementa una arquitectura de microservicios.',
    date: '2024-07-18',
    time: '20:00',
    participants: 6,
    maxParticipants: 12,
    stacks: ['Node.js', 'Docker', 'RabbitMQ'],
    value: 4.8,
  },
  {
    id: '7',
    dificulty: 'principiante',
    title: 'Introducción a Git y GitHub',
    description: 'Aprende control de versiones y colaboración en proyectos.',
    date: '2024-07-20',
    time: '15:00',
    participants: 15,
    maxParticipants: 30,
    stacks: ['Git', 'GitHub'],
    value: 4.1,
  },
  {
    id: '8',
    dificulty: 'intermedio',
    title: 'Testing en JavaScript',
    description: 'Escribe pruebas unitarias y de integración con Jest.',
    date: '2024-07-22',
    time: '17:30',
    participants: 7,
    maxParticipants: 16,
    stacks: ['JavaScript', 'Jest'],
    value: 4.0,
  },
  {
    id: '9',
    dificulty: 'avanzado',
    title: 'Optimización de rendimiento en React',
    description: 'Mejora el rendimiento de aplicaciones React complejas.',
    date: '2024-07-25',
    time: '19:00',
    participants: 4,
    maxParticipants: 10,
    stacks: ['React', 'TypeScript', 'Web Performance'],
    value: 4.9,
  },
  {
    id: '10',
    dificulty: 'principiante',
    title: 'Introducción a Python',
    description: 'Aprende los conceptos básicos de programación con Python.',
    date: '2024-07-27',
    time: '16:30',
    participants: 13,
    maxParticipants: 25,
    stacks: ['Python'],
    value: 4.0,
  },
  {
    id: '11',
    dificulty: 'intermedio',
    title: 'Desarrollo móvil con React Native',
    description: 'Crea tu primera app móvil multiplataforma.',
    date: '2024-07-29',
    time: '18:00',
    participants: 8,
    maxParticipants: 15,
    stacks: ['React Native', 'JavaScript'],
    value: 4.4,
  },
  {
    id: '12',
    dificulty: 'avanzado',
    title: 'Machine Learning con Python',
    description: 'Implementa modelos de machine learning básicos.',
    date: '2024-08-01',
    time: '20:30',
    participants: 5,
    maxParticipants: 10,
    stacks: ['Python', 'scikit-learn', 'Pandas'],
    value: 5.0,
  },
  {
    id: '13',
    dificulty: 'principiante',
    title: 'Diseño responsivo',
    description: 'Aprende a crear sitios web que se adapten a cualquier dispositivo.',
    date: '2024-08-03',
    time: '17:00',
    participants: 14,
    maxParticipants: 28,
    stacks: ['HTML', 'CSS', 'Responsive Design'],
    value: 4.2,
  },
  {
    id: '14',
    dificulty: 'intermedio',
    title: 'Autenticación con JWT',
    description: 'Implementa autenticación segura en tus APIs.',
    date: '2024-08-05',
    time: '19:00',
    participants: 7,
    maxParticipants: 14,
    stacks: ['Node.js', 'JWT', 'Express'],
    value: 4.5,
  },
  {
    id: '15',
    dificulty: 'avanzado',
    title: 'GraphQL avanzado',
    description: 'Construye APIs eficientes y flexibles con GraphQL.',
    date: '2024-08-08',
    time: '20:00',
    participants: 4,
    maxParticipants: 8,
    stacks: ['GraphQL', 'Node.js', 'TypeScript'],
    value: 4.7,
  },
]
